apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: immich
  name: immich-env
data:
  DB_DATA_LOCATION: ./postgres
  DB_DATABASE_NAME: immich
  DB_PASSWORD: postgres
  DB_USERNAME: postgres
  IMMICH_VERSION: release
  UPLOAD_LOCATION: ./library
